"""Export the dashboard dataset as JSON for the docs/ web app.

The React app in dashboard-app/ is static; this file is its only data source.
It is regenerated by every daily run (and by `trendpulse dashboard`), so the
published app updates daily without being rebuilt.
"""
from __future__ import annotations

import json
import logging
from datetime import date as _date
from datetime import datetime, timezone
from pathlib import Path

from trendpulse.entities import competitor_matcher
from trendpulse.gaps import citation_gaps, citation_summary
from trendpulse.keywords import CHANNELS, channels_for, excluded_keywords
from trendpulse.seasonality import upcoming_events
from trendpulse.storage import Store

log = logging.getLogger(__name__)


def build_payload(store: Store, cfg: dict) -> dict:
    cur = store.conn.execute("SELECT MAX(date) FROM scores")
    score_date = (cur.fetchone() or [None])[0]
    is_comp = competitor_matcher(cfg)
    excluded = excluded_keywords(cfg)

    def focus(horizon: str, channel: str, limit: int = 20) -> list[dict]:
        rows = store.latest_scores(score_date, horizon, channel,
                                   limit=limit + len(excluded))
        out = []
        for kw, score, delta, vel in rows:
            if kw in excluded:
                continue
            out.append({"keyword": kw, "score": round(score, 1),
                        "delta": round(delta, 3), "velocity": round(vel, 2),
                        "competitor": is_comp(kw),
                        "channels": sorted(channels_for(kw, cfg))})
        return out[:limit]

    horizons = list(cfg["model"]["horizons"]) if score_date else []
    focus_data = {h: {c: focus(h, c) for c in CHANNELS} for h in horizons}

    # Evidence for the strongest week picks (the "why" behind each card).
    evidence: dict[str, list[str]] = {}
    for channel in CHANNELS:
        for row in (focus_data.get("week", {}).get(channel) or [])[:6]:
            kw = row["keyword"]
            if kw not in evidence:
                items = store.recent_discoveries(kw, days=30, limit=2)
                evidence[kw] = [ctx[:140] for _d, ctx, _s in items if ctx]

    split = store.entity_mention_split(days=7)
    visibility = store.entity_visibility(days=7)
    summary = citation_summary(store, cfg, days=30)
    gaps = citation_gaps(store, cfg, days=30, limit=12)
    events = upcoming_events(cfg, _date.today(), within_days=120)

    brand_sov = next((s for _e, k, _c, s in visibility if k == "brand"), None)
    brand_rank = next((i + 1 for i, (_e, k, _c, _s) in enumerate(visibility)
                       if k == "brand"), None)
    own_citation = next((share for _d, _c, share, r in summary if r == "own"), None)
    n_keywords = store.conn.execute(
        "SELECT COUNT(DISTINCT keyword) FROM scores WHERE date = ?",
        (score_date,)).fetchone()[0] if score_date else 0

    mae: dict[str, float] = {}
    for _t, horizon, _n, value, note in store.model_runs(limit=12):  # newest first
        if note == "ok" and value is not None and horizon not in mae:
            mae[horizon] = round(value, 4)

    return {
        "meta": {
            "project": cfg.get("project", "TrendPulse"),
            "market": cfg.get("market", ""),
            "generated": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "scoreDate": score_date,
            "horizons": horizons,
            "channels": list(CHANNELS),
            "modelMae": mae,
        },
        "kpis": {
            "shareOfVoice": round(brand_sov, 1) if brand_sov is not None else None,
            "sovRank": brand_rank,
            "citationShare": round(own_citation, 1) if own_citation is not None else None,
            "citationLeader": ({"domain": summary[0][0], "share": round(summary[0][2], 1),
                                "own": summary[0][3] == "own"} if summary else None),
            "keywordsTracked": n_keywords,
            "openGaps": len(gaps),
        },
        "shareOfVoice": [
            {"entity": e, "kind": k, "ai": round(ai, 0), "community": round(com, 0)}
            for e, k, ai, com in split[:14]],
        "citations": [
            {"domain": d, "count": c, "share": round(share, 1), "role": r}
            for d, c, share, r in summary[:14]],
        "gaps": [{"prompt": g["prompt"], "domains": g["domains"][:5],
                  "models": g["models"][:5]} for g in gaps],
        "focus": focus_data,
        "evidence": evidence,
        "events": [{"name": e.name, "start": str(e.start),
                    "end": str(e.end) if e.end else None,
                    "expected": bool(e.expected), "regions": list(e.regions or []),
                    "action": e.action or "",
                    "keywords": list(e.keywords or []),
                    "daysUntil": e.days_until(_date.today()),
                    "prepNow": e.in_prep_window(_date.today()),
                    "active": e.is_active(_date.today())} for e in events],
    }


def export_data(store: Store, cfg: dict, paths: list[Path]) -> None:
    payload = json.dumps(build_payload(store, cfg), ensure_ascii=False)
    for path in paths:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(payload, encoding="utf-8")
    log.info("dashboard data exported to %s", ", ".join(str(p) for p in paths))
